# Build website
[build]
  command = "yarn run build:prod"
  publish = "./dist/"
  ignore = "exit 0"

# Terry Pratchett homage
[[headers]]
  for = "/*"
  [headers.values]
    X-Clacks-Overhead = "GNU Terry Pratchett"

