version: 2.1

aliases:
  - &defaults
    docker:
      - image: circleci/node:12.12.0
  # Git needs to know email and name so it can push commits
  - &configure_git
    run:
      name: 'Configuring git'
      command: |
        git config --global user.email "tim@pixelastic.com"
        git config --global user.name "pixelastic"
  # Adds all the ssh keys configured in CircleCI UI
  - &add_git_ssh_write_key add_ssh_keys
  # Sets the read/write key as the default one
  - &use_git_ssh_write_key
    run: 'mv ~/.ssh/id_rsa_61ab84b7ad821790660df00cc477f926 ~/.ssh/id_rsa'
  - &restore_cache
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  - &yarn_install
    run: 'yarn install'
  - &save_cache
    save_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  ci:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run: 'yarn run ci'
  # This will fetch remote data, update it locally, commit and index to algolia
  dailyUpdate:
    <<: *defaults
    steps:
      - *configure_git
      - *add_git_ssh_write_key
      - *use_git_ssh_write_key
      - checkout
      - *restore_cache
      - *yarn_install
      - *save_cache
      - run: 'yarn run ci:dailyUpdate'

workflows:
  version: 2
  # On every commit
  commit:
    jobs:
      - ci
  # Once a week
  dailyUpdate:
    triggers:
      - schedule:
          cron: '0 1 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - dailyUpdate
